spring.application.name=my-project-sboot
spring.datasource.url=jdbc:sqlite:my_data_base.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.error.whitelabel.enabled=false
server.servlet.context-path=/